//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.12.03 at 06:58:04 PM PST
//

package edu.scripps.yates.shared.model.projectCreator.excel;

public class ConditionLabelType {

	protected String conditionRef;
	protected String labelRef;

	/**
	 * Gets the value of the conditionRef property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getConditionRef() {
		return conditionRef;
	}

	/**
	 * Sets the value of the conditionRef property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setConditionRef(String value) {
		conditionRef = value;
	}

	/**
	 * Gets the value of the labelRef property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLabelRef() {
		return labelRef;
	}

	/**
	 * Sets the value of the labelRef property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLabelRef(String value) {
		labelRef = value;
	}

}
