//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.12.03 at 06:58:04 PM PST
//

package edu.scripps.yates.shared.model.projectCreator.excel;

import java.io.Serializable;

import edu.scripps.yates.shared.model.FileFormat;

public class FileTypeBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8869152503259985451L;
	protected FileFormat format;
	protected SheetsTypeBean sheets;
	protected String id;
	protected String url;
	protected String name;
	protected String serverRef;
	protected String relativePath;
	protected FastaDigestionBean fastaDigestion;

	/**
	 * Gets the value of the format property.
	 * 
	 * @return possible object is {@link FormatTypeBean }
	 * 
	 */
	public FileFormat getFormat() {
		return format;
	}

	/**
	 * Sets the value of the format property.
	 * 
	 * @param value allowed object is {@link FormatTypeBean }
	 * 
	 */
	public void setFormat(FileFormat value) {
		format = value;
	}

	/**
	 * Gets the value of the sheets property.
	 * 
	 * @return possible object is {@link SheetsTypeBean }
	 * 
	 */
	public SheetsTypeBean getSheets() {
		return sheets;
	}

	/**
	 * Sets the value of the sheets property.
	 * 
	 * @param value allowed object is {@link SheetsTypeBean }
	 * 
	 */
	public void setSheets(SheetsTypeBean value) {
		sheets = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		id = value;
	}

	/**
	 * Gets the value of the url property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * Sets the value of the url property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setUrl(String value) {
		url = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		name = value;
	}

	/**
	 * Gets the value of the serverRef property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getServerRef() {
		return serverRef;
	}

	/**
	 * Sets the value of the serverRef property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setServerRef(String value) {
		serverRef = value;
	}

	/**
	 * Gets the value of the relativePath property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRelativePath() {
		return relativePath;
	}

	/**
	 * Sets the value of the relativePath property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setRelativePath(String value) {
		relativePath = value;
	}

	public void setFastaDigestion(FastaDigestionBean fastaDigestion) {
		this.fastaDigestion = fastaDigestion;
	}

	/**
	 * @return the fastaDigestion
	 */
	public FastaDigestionBean getFastaDigestion() {
		return fastaDigestion;
	}

}
