//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.12.03 at 06:58:04 PM PST
//

package edu.scripps.yates.shared.model.projectCreator.excel;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import edu.scripps.yates.shared.model.PrincipalInvestigatorBean;
import edu.scripps.yates.shared.model.interfaces.HasId;

public class ProjectTypeBean extends HasId implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -2906960563135631178L;
	protected String description;
	protected ExperimentalConditionsTypeBean experimentalConditions;
	protected RatiosTypeBean ratios;
	protected MsRunsTypeBean msRuns;
	protected ExperimentalDesignTypeBean experimentalDesign;
	protected PrincipalInvestigatorBean principalInvestigator;
	protected List<String> instruments;
	protected String name;
	protected Boolean quantitative;
	protected Date releaseDate;
	protected String tag;

	/**
	 * Gets the value of the description property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setDescription(String value) {
		description = value;
	}

	/**
	 * Gets the value of the experimentalConditions property.
	 *
	 * @return possible object is {@link ExperimentalConditionsTypeBean }
	 *
	 */
	public ExperimentalConditionsTypeBean getExperimentalConditions() {
		return experimentalConditions;
	}

	/**
	 * Sets the value of the experimentalConditions property.
	 *
	 * @param value allowed object is {@link ExperimentalConditionsTypeBean }
	 *
	 */
	public void setExperimentalConditions(ExperimentalConditionsTypeBean value) {
		experimentalConditions = value;
	}

	/**
	 * Gets the value of the ratios property.
	 *
	 * @return possible object is {@link RatiosTypeBean }
	 *
	 */
	public RatiosTypeBean getRatios() {
		return ratios;
	}

	/**
	 * Sets the value of the ratios property.
	 *
	 * @param value allowed object is {@link RatiosTypeBean }
	 *
	 */
	public void setRatios(RatiosTypeBean value) {
		ratios = value;
	}

	/**
	 * Gets the value of the msRuns property.
	 *
	 * @return possible object is {@link MsRunsTypeBean }
	 *
	 */
	public MsRunsTypeBean getMsRuns() {
		return msRuns;
	}

	/**
	 * Sets the value of the msRuns property.
	 *
	 * @param value allowed object is {@link MsRunsTypeBean }
	 *
	 */
	public void setMsRuns(MsRunsTypeBean value) {
		msRuns = value;
	}

	/**
	 * Gets the value of the experimentalDesign property.
	 *
	 * @return possible object is {@link ExperimentalDesignTypeBean }
	 *
	 */
	public ExperimentalDesignTypeBean getExperimentalDesign() {
		return experimentalDesign;
	}

	/**
	 * Sets the value of the experimentalDesign property.
	 *
	 * @param value allowed object is {@link ExperimentalDesignTypeBean }
	 *
	 */
	public void setExperimentalDesign(ExperimentalDesignTypeBean value) {
		experimentalDesign = value;
	}

	/**
	 * Gets the value of the name property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setName(String value) {
		name = value;
	}

	/**
	 * Gets the value of the quantitative property.
	 *
	 * @return possible object is {@link Boolean }
	 *
	 */
	public Boolean isQuantitative() {
		return quantitative;
	}

	/**
	 * Sets the value of the quantitative property.
	 *
	 * @param value allowed object is {@link Boolean }
	 *
	 */
	public void setQuantitative(Boolean value) {
		quantitative = value;
	}

	/**
	 * Gets the value of the releaseDate property.
	 *
	 * @return possible object is {@link Date }
	 *
	 */
	public Date getReleaseDate() {
		return releaseDate;
	}

	/**
	 * Sets the value of the releaseDate property.
	 *
	 * @param value allowed object is {@link Date }
	 *
	 */
	public void setReleaseDate(Date value) {
		releaseDate = value;
	}

	/**
	 * Gets the value of the tag property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * Sets the value of the tag property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setTag(String value) {
		tag = value;
	}

	@Override
	public String getId() {
		return getTag();
	}

	public PrincipalInvestigatorBean getPrincipalInvestigator() {
		return principalInvestigator;
	}

	public void setPrincipalInvestigator(PrincipalInvestigatorBean principalInvestigator) {
		this.principalInvestigator = principalInvestigator;
	}

	public List<String> getInstruments() {
		return instruments;
	}

	public void setInstruments(List<String> instruments) {
		this.instruments = instruments;
	}

}
