//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.12.03 at 06:58:04 PM PST
//

package edu.scripps.yates.shared.model.projectCreator.excel;

import java.io.Serializable;

public class ProteinAccessionTypeBean implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -4883707403998436346L;
	protected String regexp;
	protected boolean groups;
	protected String groupSeparator;
	protected String columnRef;

	/**
	 * Gets the value of the regexp property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getRegexp() {
		return regexp;
	}

	/**
	 * Sets the value of the regexp property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setRegexp(String value) {
		regexp = value;
	}

	/**
	 * Gets the value of the groups property.
	 *
	 */
	public boolean isGroups() {
		return groups;
	}

	/**
	 * Sets the value of the groups property.
	 *
	 */
	public void setGroups(boolean value) {
		groups = value;
	}

	/**
	 * Gets the value of the groupSeparator property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getGroupSeparator() {
		return groupSeparator;
	}

	/**
	 * Sets the value of the groupSeparator property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setGroupSeparator(String value) {
		groupSeparator = value;
	}

	/**
	 * Gets the value of the columnRef property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getColumnRef() {
		return columnRef;
	}

	/**
	 * Sets the value of the columnRef property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setColumnRef(String value) {
		columnRef = value;
	}

}
