//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.12.03 at 06:58:04 PM PST
//

package edu.scripps.yates.shared.model.projectCreator.excel;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class QuantificationInfoTypeBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1679784873193378791L;
	protected List<QuantificationExcelTypeBean> excelQuantInfo;
	protected List<RemoteInfoTypeBean> remoteFilesQuantInfo;

	/**
	 * Gets the value of the excelQuantInfo property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the excelQuantInfo property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getExcelQuantInfo().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link QuantificationExcelTypeBean }
	 * 
	 * 
	 */
	public List<QuantificationExcelTypeBean> getExcelQuantInfo() {
		if (excelQuantInfo == null) {
			excelQuantInfo = new ArrayList<QuantificationExcelTypeBean>();
		}
		return excelQuantInfo;
	}

	/**
	 * Gets the value of the remoteFilesQuantInfo property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the remoteFilesQuantInfo property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRemoteFilesQuantInfo().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link RemoteInfoTypeBean }
	 * 
	 * 
	 */
	public List<RemoteInfoTypeBean> getRemoteFilesQuantInfo() {
		if (remoteFilesQuantInfo == null) {
			remoteFilesQuantInfo = new ArrayList<RemoteInfoTypeBean>();
		}
		return remoteFilesQuantInfo;
	}

}
