//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.12.03 at 06:58:04 PM PST
//

package edu.scripps.yates.shared.model.projectCreator.excel;

import java.io.Serializable;

public class RatiosTypeBean implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -4233079953227584212L;
	protected ProteinRatiosTypeBean proteinAmountRatios;
	protected PeptideRatiosTypeBean peptideAmountRatios;
	protected PsmRatiosTypeBean psmAmountRatios;

	/**
	 * @return the proteinAmountRatios
	 */
	public ProteinRatiosTypeBean getProteinAmountRatios() {
		return proteinAmountRatios;
	}

	/**
	 * @param proteinAmountRatios
	 *            the proteinAmountRatios to set
	 */
	public void setProteinAmountRatios(ProteinRatiosTypeBean proteinAmountRatios) {
		this.proteinAmountRatios = proteinAmountRatios;
	}

	/**
	 * @return the peptideAmountRatios
	 */
	public PeptideRatiosTypeBean getPeptideAmountRatios() {
		return peptideAmountRatios;
	}

	/**
	 * @param peptideAmountRatios
	 *            the peptideAmountRatios to set
	 */
	public void setPeptideAmountRatios(PeptideRatiosTypeBean peptideAmountRatios) {
		this.peptideAmountRatios = peptideAmountRatios;
	}

	/**
	 * @return the psmAmountRatios
	 */
	public PsmRatiosTypeBean getPsmAmountRatios() {
		return psmAmountRatios;
	}

	/**
	 * @param psmAmountRatios
	 *            the psmAmountRatios to set
	 */
	public void setPsmAmountRatios(PsmRatiosTypeBean psmAmountRatios) {
		this.psmAmountRatios = psmAmountRatios;
	}

}
