//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.12.03 at 06:58:04 PM PST
//

package edu.scripps.yates.shared.model.projectCreator.excel;

import java.io.Serializable;

public class ScoreTypeBean implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 10249139013400745L;
	protected String description;
	protected String scoreName;
	protected String scoreType;
	protected String columnRef;

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		description = value;
	}

	/**
	 * Gets the value of the scoreName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getScoreName() {
		return scoreName;
	}

	/**
	 * Sets the value of the scoreName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setScoreName(String value) {
		scoreName = value;
	}

	/**
	 * Gets the value of the scoreType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getScoreType() {
		return scoreType;
	}

	/**
	 * Sets the value of the scoreType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setScoreType(String value) {
		scoreType = value;
	}

	/**
	 * Gets the value of the columnRef property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getColumnRef() {
		return columnRef;
	}

	/**
	 * Sets the value of the columnRef property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setColumnRef(String value) {
		columnRef = value;
	}

}
