//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.17 at 12:09:13 PM PDT 
//


package edu.scripps.yates.annotations.omim.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.scripps.yates.uniprot.omim.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.scripps.yates.uniprot.omim.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Omim.EntryList.Entry.Titles }
     * 
     */
    public Omim.EntryList.Entry.Titles createOmimEntryListEntryTitles() {
        return new Omim.EntryList.Entry.Titles();
    }

    /**
     * Create an instance of {@link Omim }
     * 
     */
    public Omim createOmim() {
        return new Omim();
    }

    /**
     * Create an instance of {@link Omim.EntryList.Entry }
     * 
     */
    public Omim.EntryList.Entry createOmimEntryListEntry() {
        return new Omim.EntryList.Entry();
    }

    /**
     * Create an instance of {@link Omim.EntryList }
     * 
     */
    public Omim.EntryList createOmimEntryList() {
        return new Omim.EntryList();
    }

}
