//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 03:44:17 PM PST 
//


package edu.scripps.yates.excel.proteindb.importcfg.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for excel_amount_ratioType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="excel_amount_ratioType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="protein_accession" type="{}protein_accessionType"/>
 *           &lt;element name="peptide_sequence" type="{}sequenceType"/>
 *           &lt;element name="psm_id" type="{}psmType"/>
 *         &lt;/choice>
 *         &lt;element name="numerator" type="{}conditionRefType"/>
 *         &lt;element name="denominator" type="{}conditionRefType"/>
 *         &lt;element name="ratio_score" type="{}scoreType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="columnRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="msRunRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "excel_amount_ratioType", propOrder = {
    "proteinAccession",
    "peptideSequence",
    "psmId",
    "numerator",
    "denominator",
    "ratioScore"
})
public class ExcelAmountRatioType {

    @XmlElement(name = "protein_accession")
    protected ProteinAccessionType proteinAccession;
    @XmlElement(name = "peptide_sequence")
    protected SequenceType peptideSequence;
    @XmlElement(name = "psm_id")
    protected PsmType psmId;
    @XmlElement(required = true)
    protected ConditionRefType numerator;
    @XmlElement(required = true)
    protected ConditionRefType denominator;
    @XmlElement(name = "ratio_score")
    protected ScoreType ratioScore;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "columnRef", required = true)
    protected String columnRef;
    @XmlAttribute(name = "msRunRef")
    protected String msRunRef;

    /**
     * Gets the value of the proteinAccession property.
     * 
     * @return
     *     possible object is
     *     {@link ProteinAccessionType }
     *     
     */
    public ProteinAccessionType getProteinAccession() {
        return proteinAccession;
    }

    /**
     * Sets the value of the proteinAccession property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinAccessionType }
     *     
     */
    public void setProteinAccession(ProteinAccessionType value) {
        this.proteinAccession = value;
    }

    /**
     * Gets the value of the peptideSequence property.
     * 
     * @return
     *     possible object is
     *     {@link SequenceType }
     *     
     */
    public SequenceType getPeptideSequence() {
        return peptideSequence;
    }

    /**
     * Sets the value of the peptideSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequenceType }
     *     
     */
    public void setPeptideSequence(SequenceType value) {
        this.peptideSequence = value;
    }

    /**
     * Gets the value of the psmId property.
     * 
     * @return
     *     possible object is
     *     {@link PsmType }
     *     
     */
    public PsmType getPsmId() {
        return psmId;
    }

    /**
     * Sets the value of the psmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PsmType }
     *     
     */
    public void setPsmId(PsmType value) {
        this.psmId = value;
    }

    /**
     * Gets the value of the numerator property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionRefType }
     *     
     */
    public ConditionRefType getNumerator() {
        return numerator;
    }

    /**
     * Sets the value of the numerator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionRefType }
     *     
     */
    public void setNumerator(ConditionRefType value) {
        this.numerator = value;
    }

    /**
     * Gets the value of the denominator property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionRefType }
     *     
     */
    public ConditionRefType getDenominator() {
        return denominator;
    }

    /**
     * Sets the value of the denominator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionRefType }
     *     
     */
    public void setDenominator(ConditionRefType value) {
        this.denominator = value;
    }

    /**
     * Gets the value of the ratioScore property.
     * 
     * @return
     *     possible object is
     *     {@link ScoreType }
     *     
     */
    public ScoreType getRatioScore() {
        return ratioScore;
    }

    /**
     * Sets the value of the ratioScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScoreType }
     *     
     */
    public void setRatioScore(ScoreType value) {
        this.ratioScore = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the columnRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnRef() {
        return columnRef;
    }

    /**
     * Sets the value of the columnRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnRef(String value) {
        this.columnRef = value;
    }

    /**
     * Gets the value of the msRunRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsRunRef() {
        return msRunRef;
    }

    /**
     * Sets the value of the msRunRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsRunRef(String value) {
        this.msRunRef = value;
    }

}
