//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 03:44:17 PM PST 
//


package edu.scripps.yates.excel.proteindb.importcfg.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for experimentalDesignType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="experimentalDesignType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sampleSet" type="{}sampleSetType"/>
 *         &lt;element name="organismSet" type="{}organismSetType"/>
 *         &lt;element name="tissueSet" type="{}tissueSetType"/>
 *         &lt;element name="labelSet" type="{}labelSetType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "experimentalDesignType", propOrder = {
    "sampleSet",
    "organismSet",
    "tissueSet",
    "labelSet"
})
public class ExperimentalDesignType {

    @XmlElement(required = true)
    protected SampleSetType sampleSet;
    @XmlElement(required = true)
    protected OrganismSetType organismSet;
    @XmlElement(required = true)
    protected TissueSetType tissueSet;
    protected LabelSetType labelSet;

    /**
     * Gets the value of the sampleSet property.
     * 
     * @return
     *     possible object is
     *     {@link SampleSetType }
     *     
     */
    public SampleSetType getSampleSet() {
        return sampleSet;
    }

    /**
     * Sets the value of the sampleSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link SampleSetType }
     *     
     */
    public void setSampleSet(SampleSetType value) {
        this.sampleSet = value;
    }

    /**
     * Gets the value of the organismSet property.
     * 
     * @return
     *     possible object is
     *     {@link OrganismSetType }
     *     
     */
    public OrganismSetType getOrganismSet() {
        return organismSet;
    }

    /**
     * Sets the value of the organismSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganismSetType }
     *     
     */
    public void setOrganismSet(OrganismSetType value) {
        this.organismSet = value;
    }

    /**
     * Gets the value of the tissueSet property.
     * 
     * @return
     *     possible object is
     *     {@link TissueSetType }
     *     
     */
    public TissueSetType getTissueSet() {
        return tissueSet;
    }

    /**
     * Sets the value of the tissueSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TissueSetType }
     *     
     */
    public void setTissueSet(TissueSetType value) {
        this.tissueSet = value;
    }

    /**
     * Gets the value of the labelSet property.
     * 
     * @return
     *     possible object is
     *     {@link LabelSetType }
     *     
     */
    public LabelSetType getLabelSet() {
        return labelSet;
    }

    /**
     * Sets the value of the labelSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelSetType }
     *     
     */
    public void setLabelSet(LabelSetType value) {
        this.labelSet = value;
    }

}
