//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 03:44:17 PM PST 
//


package edu.scripps.yates.excel.proteindb.importcfg.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for identification_InfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="identification_InfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="excel_ident_info" type="{}identification_excelType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="remoteFiles_ident_info" type="{}remote_InfoType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identification_InfoType", propOrder = {
    "excelIdentInfo",
    "remoteFilesIdentInfo"
})
public class IdentificationInfoType {

    @XmlElement(name = "excel_ident_info")
    protected List<IdentificationExcelType> excelIdentInfo;
    @XmlElement(name = "remoteFiles_ident_info")
    protected List<RemoteInfoType> remoteFilesIdentInfo;

    /**
     * Gets the value of the excelIdentInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the excelIdentInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExcelIdentInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationExcelType }
     * 
     * 
     */
    public List<IdentificationExcelType> getExcelIdentInfo() {
        if (excelIdentInfo == null) {
            excelIdentInfo = new ArrayList<IdentificationExcelType>();
        }
        return this.excelIdentInfo;
    }

    /**
     * Gets the value of the remoteFilesIdentInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remoteFilesIdentInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemoteFilesIdentInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RemoteInfoType }
     * 
     * 
     */
    public List<RemoteInfoType> getRemoteFilesIdentInfo() {
        if (remoteFilesIdentInfo == null) {
            remoteFilesIdentInfo = new ArrayList<RemoteInfoType>();
        }
        return this.remoteFilesIdentInfo;
    }

}
