//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.18 at 09:46:51 AM PST 
//


package edu.scripps.yates.excel.proteindb.importcfg.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for identification_excelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="identification_excelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="protein_accession" type="{}protein_accessionType"/>
 *         &lt;element name="protein_description" type="{}protein_descriptionType" minOccurs="0"/>
 *         &lt;element name="protein_annotations" type="{}protein_annotationsType" minOccurs="0"/>
 *         &lt;element name="protein_score" type="{}scoreType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sequence" type="{}sequenceType" minOccurs="0"/>
 *         &lt;element name="psm_id" type="{}psmType" minOccurs="0"/>
 *         &lt;element name="psm_score" type="{}scoreType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="peptide_score" type="{}scoreType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ptm_score" type="{}ptm_scoreType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="discard_decoys" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="protein_thresholds" type="{}proteinThresholdsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="msRunRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identification_excelType", propOrder = {
    "proteinAccession",
    "proteinDescription",
    "proteinAnnotations",
    "proteinScore",
    "sequence",
    "psmId",
    "psmScore",
    "peptideScore",
    "ptmScore",
    "discardDecoys",
    "proteinThresholds"
})
public class IdentificationExcelType {

    @XmlElement(name = "protein_accession", required = true)
    protected ProteinAccessionType proteinAccession;
    @XmlElement(name = "protein_description")
    protected ProteinDescriptionType proteinDescription;
    @XmlElement(name = "protein_annotations")
    protected ProteinAnnotationsType proteinAnnotations;
    @XmlElement(name = "protein_score")
    protected List<ScoreType> proteinScore;
    protected SequenceType sequence;
    @XmlElement(name = "psm_id")
    protected PsmType psmId;
    @XmlElement(name = "psm_score")
    protected List<ScoreType> psmScore;
    @XmlElement(name = "peptide_score")
    protected List<ScoreType> peptideScore;
    @XmlElement(name = "ptm_score")
    protected List<PtmScoreType> ptmScore;
    @XmlElement(name = "discard_decoys")
    protected String discardDecoys;
    @XmlElement(name = "protein_thresholds")
    protected ProteinThresholdsType proteinThresholds;
    @XmlAttribute(name = "msRunRef", required = true)
    protected String msRunRef;

    /**
     * Gets the value of the proteinAccession property.
     * 
     * @return
     *     possible object is
     *     {@link ProteinAccessionType }
     *     
     */
    public ProteinAccessionType getProteinAccession() {
        return proteinAccession;
    }

    /**
     * Sets the value of the proteinAccession property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinAccessionType }
     *     
     */
    public void setProteinAccession(ProteinAccessionType value) {
        this.proteinAccession = value;
    }

    /**
     * Gets the value of the proteinDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ProteinDescriptionType }
     *     
     */
    public ProteinDescriptionType getProteinDescription() {
        return proteinDescription;
    }

    /**
     * Sets the value of the proteinDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinDescriptionType }
     *     
     */
    public void setProteinDescription(ProteinDescriptionType value) {
        this.proteinDescription = value;
    }

    /**
     * Gets the value of the proteinAnnotations property.
     * 
     * @return
     *     possible object is
     *     {@link ProteinAnnotationsType }
     *     
     */
    public ProteinAnnotationsType getProteinAnnotations() {
        return proteinAnnotations;
    }

    /**
     * Sets the value of the proteinAnnotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinAnnotationsType }
     *     
     */
    public void setProteinAnnotations(ProteinAnnotationsType value) {
        this.proteinAnnotations = value;
    }

    /**
     * Gets the value of the proteinScore property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the proteinScore property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProteinScore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScoreType }
     * 
     * 
     */
    public List<ScoreType> getProteinScore() {
        if (proteinScore == null) {
            proteinScore = new ArrayList<ScoreType>();
        }
        return this.proteinScore;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link SequenceType }
     *     
     */
    public SequenceType getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequenceType }
     *     
     */
    public void setSequence(SequenceType value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the psmId property.
     * 
     * @return
     *     possible object is
     *     {@link PsmType }
     *     
     */
    public PsmType getPsmId() {
        return psmId;
    }

    /**
     * Sets the value of the psmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PsmType }
     *     
     */
    public void setPsmId(PsmType value) {
        this.psmId = value;
    }

    /**
     * Gets the value of the psmScore property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the psmScore property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPsmScore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScoreType }
     * 
     * 
     */
    public List<ScoreType> getPsmScore() {
        if (psmScore == null) {
            psmScore = new ArrayList<ScoreType>();
        }
        return this.psmScore;
    }

    /**
     * Gets the value of the peptideScore property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the peptideScore property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeptideScore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScoreType }
     * 
     * 
     */
    public List<ScoreType> getPeptideScore() {
        if (peptideScore == null) {
            peptideScore = new ArrayList<ScoreType>();
        }
        return this.peptideScore;
    }

    /**
     * Gets the value of the ptmScore property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ptmScore property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPtmScore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PtmScoreType }
     * 
     * 
     */
    public List<PtmScoreType> getPtmScore() {
        if (ptmScore == null) {
            ptmScore = new ArrayList<PtmScoreType>();
        }
        return this.ptmScore;
    }

    /**
     * Gets the value of the discardDecoys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscardDecoys() {
        return discardDecoys;
    }

    /**
     * Sets the value of the discardDecoys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscardDecoys(String value) {
        this.discardDecoys = value;
    }

    /**
     * Gets the value of the proteinThresholds property.
     * 
     * @return
     *     possible object is
     *     {@link ProteinThresholdsType }
     *     
     */
    public ProteinThresholdsType getProteinThresholds() {
        return proteinThresholds;
    }

    /**
     * Sets the value of the proteinThresholds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinThresholdsType }
     *     
     */
    public void setProteinThresholds(ProteinThresholdsType value) {
        this.proteinThresholds = value;
    }

    /**
     * Gets the value of the msRunRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsRunRef() {
        return msRunRef;
    }

    /**
     * Sets the value of the msRunRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsRunRef(String value) {
        this.msRunRef = value;
    }

}
