//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.18 at 09:46:51 AM PST 
//


package edu.scripps.yates.excel.proteindb.importcfg.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for protein_accessionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="protein_accessionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="regexp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="groups" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="group_separator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="columnRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "protein_accessionType", propOrder = {
    "regexp"
})
public class ProteinAccessionType {

    @XmlElement(required = true)
    protected String regexp;
    @XmlAttribute(name = "groups", required = true)
    protected boolean groups;
    @XmlAttribute(name = "group_separator")
    protected String groupSeparator;
    @XmlAttribute(name = "columnRef", required = true)
    protected String columnRef;

    /**
     * Gets the value of the regexp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegexp() {
        return regexp;
    }

    /**
     * Sets the value of the regexp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegexp(String value) {
        this.regexp = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     */
    public boolean isGroups() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     * 
     */
    public void setGroups(boolean value) {
        this.groups = value;
    }

    /**
     * Gets the value of the groupSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupSeparator() {
        return groupSeparator;
    }

    /**
     * Sets the value of the groupSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupSeparator(String value) {
        this.groupSeparator = value;
    }

    /**
     * Gets the value of the columnRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnRef() {
        return columnRef;
    }

    /**
     * Sets the value of the columnRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnRef(String value) {
        this.columnRef = value;
    }

}
