//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.18 at 09:46:51 AM PST 
//


package edu.scripps.yates.excel.proteindb.importcfg.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ratiosType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ratiosType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="protein_amount_ratios" type="{}protein_ratiosType" minOccurs="0"/>
 *         &lt;element name="peptide_amount_ratios" type="{}peptide_ratiosType" minOccurs="0"/>
 *         &lt;element name="psm_amount_ratios" type="{}psm_ratiosType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ratiosType", propOrder = {
    "proteinAmountRatios",
    "peptideAmountRatios",
    "psmAmountRatios"
})
public class RatiosType {

    @XmlElement(name = "protein_amount_ratios")
    protected ProteinRatiosType proteinAmountRatios;
    @XmlElement(name = "peptide_amount_ratios")
    protected PeptideRatiosType peptideAmountRatios;
    @XmlElement(name = "psm_amount_ratios")
    protected PsmRatiosType psmAmountRatios;

    /**
     * Gets the value of the proteinAmountRatios property.
     * 
     * @return
     *     possible object is
     *     {@link ProteinRatiosType }
     *     
     */
    public ProteinRatiosType getProteinAmountRatios() {
        return proteinAmountRatios;
    }

    /**
     * Sets the value of the proteinAmountRatios property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinRatiosType }
     *     
     */
    public void setProteinAmountRatios(ProteinRatiosType value) {
        this.proteinAmountRatios = value;
    }

    /**
     * Gets the value of the peptideAmountRatios property.
     * 
     * @return
     *     possible object is
     *     {@link PeptideRatiosType }
     *     
     */
    public PeptideRatiosType getPeptideAmountRatios() {
        return peptideAmountRatios;
    }

    /**
     * Sets the value of the peptideAmountRatios property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeptideRatiosType }
     *     
     */
    public void setPeptideAmountRatios(PeptideRatiosType value) {
        this.peptideAmountRatios = value;
    }

    /**
     * Gets the value of the psmAmountRatios property.
     * 
     * @return
     *     possible object is
     *     {@link PsmRatiosType }
     *     
     */
    public PsmRatiosType getPsmAmountRatios() {
        return psmAmountRatios;
    }

    /**
     * Sets the value of the psmAmountRatios property.
     * 
     * @param value
     *     allowed object is
     *     {@link PsmRatiosType }
     *     
     */
    public void setPsmAmountRatios(PsmRatiosType value) {
        this.psmAmountRatios = value;
    }

}
