//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 03:44:17 PM PST 
//


package edu.scripps.yates.excel.proteindb.importcfg.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for remote_InfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="remote_InfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fileRef" type="{}fileReferenceType" maxOccurs="unbounded"/>
 *         &lt;element name="discard_decoys" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="msRunRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "remote_InfoType", propOrder = {
    "fileRef",
    "discardDecoys"
})
public class RemoteInfoType {

    @XmlElement(required = true)
    protected List<FileReferenceType> fileRef;
    @XmlElement(name = "discard_decoys")
    protected String discardDecoys;
    @XmlAttribute(name = "msRunRef", required = true)
    protected String msRunRef;

    /**
     * Gets the value of the fileRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fileRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileReferenceType }
     * 
     * 
     */
    public List<FileReferenceType> getFileRef() {
        if (fileRef == null) {
            fileRef = new ArrayList<FileReferenceType>();
        }
        return this.fileRef;
    }

    /**
     * Gets the value of the discardDecoys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscardDecoys() {
        return discardDecoys;
    }

    /**
     * Sets the value of the discardDecoys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscardDecoys(String value) {
        this.discardDecoys = value;
    }

    /**
     * Gets the value of the msRunRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsRunRef() {
        return msRunRef;
    }

    /**
     * Sets the value of the msRunRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsRunRef(String value) {
        this.msRunRef = value;
    }

}
