//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 03:44:17 PM PST 
//


package edu.scripps.yates.excel.proteindb.importcfg.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for remote_files_ratioType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="remote_files_ratioType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numerator" type="{}conditionRefType"/>
 *         &lt;element name="denominator" type="{}conditionRefType"/>
 *         &lt;element name="discard_decoys" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fileRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="msRunRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "remote_files_ratioType", propOrder = {
    "numerator",
    "denominator",
    "discardDecoys"
})
public class RemoteFilesRatioType {

    @XmlElement(required = true)
    protected ConditionRefType numerator;
    @XmlElement(required = true)
    protected ConditionRefType denominator;
    @XmlElement(name = "discard_decoys")
    protected String discardDecoys;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "fileRef", required = true)
    protected String fileRef;
    @XmlAttribute(name = "msRunRef", required = true)
    protected String msRunRef;

    /**
     * Gets the value of the numerator property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionRefType }
     *     
     */
    public ConditionRefType getNumerator() {
        return numerator;
    }

    /**
     * Sets the value of the numerator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionRefType }
     *     
     */
    public void setNumerator(ConditionRefType value) {
        this.numerator = value;
    }

    /**
     * Gets the value of the denominator property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionRefType }
     *     
     */
    public ConditionRefType getDenominator() {
        return denominator;
    }

    /**
     * Sets the value of the denominator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionRefType }
     *     
     */
    public void setDenominator(ConditionRefType value) {
        this.denominator = value;
    }

    /**
     * Gets the value of the discardDecoys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscardDecoys() {
        return discardDecoys;
    }

    /**
     * Sets the value of the discardDecoys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscardDecoys(String value) {
        this.discardDecoys = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the fileRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileRef() {
        return fileRef;
    }

    /**
     * Sets the value of the fileRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileRef(String value) {
        this.fileRef = value;
    }

    /**
     * Gets the value of the msRunRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsRunRef() {
        return msRunRef;
    }

    /**
     * Sets the value of the msRunRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsRunRef(String value) {
        this.msRunRef = value;
    }

}
