//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.04 at 04:54:37 PM PDT 
//


package edu.scripps.yates.annotations.peptidematch.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.scripps.yates.uniprot.peptidematch.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PeptideMatchMatchPerPeptideMatchedProteinProteomicDBsPride_QNAME = new QName("", "pride");
    private final static QName _PeptideMatchMatchPerPeptideMatchedProteinProteomicDBsNist_QNAME = new QName("", "nist");
    private final static QName _PeptideMatchMatchPerPeptideMatchedProteinProteomicDBsPeptideAtlas_QNAME = new QName("", "peptideAtlas");
    private final static QName _PeptideMatchMatchPerPeptideMatchedProteinIedbsIedbID_QNAME = new QName("", "iedbID");
    private final static QName _PeptideMatchMatchPerPeptideMatchedProteinMatchRangesMatchRangeLEqiPos_QNAME = new QName("", "lEqiPos");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.scripps.yates.uniprot.peptidematch.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PeptideMatch.MatchPerPeptide }
     * 
     */
    public PeptideMatch.MatchPerPeptide createPeptideMatchMatchPerPeptide() {
        return new PeptideMatch.MatchPerPeptide();
    }

    /**
     * Create an instance of {@link PeptideMatch.PerPeptideMatchSummaryReport }
     * 
     */
    public PeptideMatch.PerPeptideMatchSummaryReport createPeptideMatchPerPeptideMatchSummaryReport() {
        return new PeptideMatch.PerPeptideMatchSummaryReport();
    }

    /**
     * Create an instance of {@link PeptideMatch.QueryInfo }
     * 
     */
    public PeptideMatch.QueryInfo createPeptideMatchQueryInfo() {
        return new PeptideMatch.QueryInfo();
    }

    /**
     * Create an instance of {@link PeptideMatch.MatchPerPeptide.MatchedProtein.ProteomicDBs }
     * 
     */
    public PeptideMatch.MatchPerPeptide.MatchedProtein.ProteomicDBs createPeptideMatchMatchPerPeptideMatchedProteinProteomicDBs() {
        return new PeptideMatch.MatchPerPeptide.MatchedProtein.ProteomicDBs();
    }

    /**
     * Create an instance of {@link PeptideMatch.MatchPerPeptide.MatchedProtein.Iedbs }
     * 
     */
    public PeptideMatch.MatchPerPeptide.MatchedProtein.Iedbs createPeptideMatchMatchPerPeptideMatchedProteinIedbs() {
        return new PeptideMatch.MatchPerPeptide.MatchedProtein.Iedbs();
    }

    /**
     * Create an instance of {@link PeptideMatch.QueryInfo.SequenceDataSet }
     * 
     */
    public PeptideMatch.QueryInfo.SequenceDataSet createPeptideMatchQueryInfoSequenceDataSet() {
        return new PeptideMatch.QueryInfo.SequenceDataSet();
    }

    /**
     * Create an instance of {@link PeptideMatch.PerPeptideMatchSummaryReport.PerPeptideMatchInfo }
     * 
     */
    public PeptideMatch.PerPeptideMatchSummaryReport.PerPeptideMatchInfo createPeptideMatchPerPeptideMatchSummaryReportPerPeptideMatchInfo() {
        return new PeptideMatch.PerPeptideMatchSummaryReport.PerPeptideMatchInfo();
    }

    /**
     * Create an instance of {@link PeptideMatch.MatchPerPeptide.MatchedProtein.MatchRanges.MatchRange }
     * 
     */
    public PeptideMatch.MatchPerPeptide.MatchedProtein.MatchRanges.MatchRange createPeptideMatchMatchPerPeptideMatchedProteinMatchRangesMatchRange() {
        return new PeptideMatch.MatchPerPeptide.MatchedProtein.MatchRanges.MatchRange();
    }

    /**
     * Create an instance of {@link PeptideMatch.MatchPerPeptide.MatchedProtein.Organism }
     * 
     */
    public PeptideMatch.MatchPerPeptide.MatchedProtein.Organism createPeptideMatchMatchPerPeptideMatchedProteinOrganism() {
        return new PeptideMatch.MatchPerPeptide.MatchedProtein.Organism();
    }

    /**
     * Create an instance of {@link PeptideMatch.PerProteinMatchSummaryReport.PerProteinMatchInfo.MatchingPeptides }
     * 
     */
    public PeptideMatch.PerProteinMatchSummaryReport.PerProteinMatchInfo.MatchingPeptides createPeptideMatchPerProteinMatchSummaryReportPerProteinMatchInfoMatchingPeptides() {
        return new PeptideMatch.PerProteinMatchSummaryReport.PerProteinMatchInfo.MatchingPeptides();
    }

    /**
     * Create an instance of {@link PeptideMatch.MatchPerPeptide.MatchedProtein.MatchRanges }
     * 
     */
    public PeptideMatch.MatchPerPeptide.MatchedProtein.MatchRanges createPeptideMatchMatchPerPeptideMatchedProteinMatchRanges() {
        return new PeptideMatch.MatchPerPeptide.MatchedProtein.MatchRanges();
    }

    /**
     * Create an instance of {@link PeptideMatch }
     * 
     */
    public PeptideMatch createPeptideMatch() {
        return new PeptideMatch();
    }

    /**
     * Create an instance of {@link PeptideMatch.PerProteinMatchSummaryReport }
     * 
     */
    public PeptideMatch.PerProteinMatchSummaryReport createPeptideMatchPerProteinMatchSummaryReport() {
        return new PeptideMatch.PerProteinMatchSummaryReport();
    }

    /**
     * Create an instance of {@link PeptideMatch.PerProteinMatchSummaryReport.PerProteinMatchInfo }
     * 
     */
    public PeptideMatch.PerProteinMatchSummaryReport.PerProteinMatchInfo createPeptideMatchPerProteinMatchSummaryReportPerProteinMatchInfo() {
        return new PeptideMatch.PerProteinMatchSummaryReport.PerProteinMatchInfo();
    }

    /**
     * Create an instance of {@link PeptideMatch.MatchPerPeptide.MatchedProtein.ProteinID }
     * 
     */
    public PeptideMatch.MatchPerPeptide.MatchedProtein.ProteinID createPeptideMatchMatchPerPeptideMatchedProteinProteinID() {
        return new PeptideMatch.MatchPerPeptide.MatchedProtein.ProteinID();
    }

    /**
     * Create an instance of {@link PeptideMatch.MatchPerPeptide.MatchedProtein }
     * 
     */
    public PeptideMatch.MatchPerPeptide.MatchedProtein createPeptideMatchMatchPerPeptideMatchedProtein() {
        return new PeptideMatch.MatchPerPeptide.MatchedProtein();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pride", scope = PeptideMatch.MatchPerPeptide.MatchedProtein.ProteomicDBs.class)
    public JAXBElement<String> createPeptideMatchMatchPerPeptideMatchedProteinProteomicDBsPride(String value) {
        return new JAXBElement<String>(_PeptideMatchMatchPerPeptideMatchedProteinProteomicDBsPride_QNAME, String.class, PeptideMatch.MatchPerPeptide.MatchedProtein.ProteomicDBs.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nist", scope = PeptideMatch.MatchPerPeptide.MatchedProtein.ProteomicDBs.class)
    public JAXBElement<String> createPeptideMatchMatchPerPeptideMatchedProteinProteomicDBsNist(String value) {
        return new JAXBElement<String>(_PeptideMatchMatchPerPeptideMatchedProteinProteomicDBsNist_QNAME, String.class, PeptideMatch.MatchPerPeptide.MatchedProtein.ProteomicDBs.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "peptideAtlas", scope = PeptideMatch.MatchPerPeptide.MatchedProtein.ProteomicDBs.class)
    public JAXBElement<String> createPeptideMatchMatchPerPeptideMatchedProteinProteomicDBsPeptideAtlas(String value) {
        return new JAXBElement<String>(_PeptideMatchMatchPerPeptideMatchedProteinProteomicDBsPeptideAtlas_QNAME, String.class, PeptideMatch.MatchPerPeptide.MatchedProtein.ProteomicDBs.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "iedbID", scope = PeptideMatch.MatchPerPeptide.MatchedProtein.Iedbs.class)
    public JAXBElement<Integer> createPeptideMatchMatchPerPeptideMatchedProteinIedbsIedbID(Integer value) {
        return new JAXBElement<Integer>(_PeptideMatchMatchPerPeptideMatchedProteinIedbsIedbID_QNAME, Integer.class, PeptideMatch.MatchPerPeptide.MatchedProtein.Iedbs.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lEqiPos", scope = PeptideMatch.MatchPerPeptide.MatchedProtein.MatchRanges.MatchRange.class)
    public JAXBElement<Integer> createPeptideMatchMatchPerPeptideMatchedProteinMatchRangesMatchRangeLEqiPos(Integer value) {
        return new JAXBElement<Integer>(_PeptideMatchMatchPerPeptideMatchedProteinMatchRangesMatchRangeLEqiPos_QNAME, Integer.class, PeptideMatch.MatchPerPeptide.MatchedProtein.MatchRanges.MatchRange.class, value);
    }

}
