//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 08:56:44 AM PDT 
//


package edu.scripps.yates.annotations.uniref.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.scripps.yates.uniprot.uniref.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.scripps.yates.uniprot.uniref.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UniRef }
     * 
     */
    public UniRef createUniRef() {
        return new UniRef();
    }

    /**
     * Create an instance of {@link DbReferenceType }
     * 
     */
    public DbReferenceType createDbReferenceType() {
        return new DbReferenceType();
    }

    /**
     * Create an instance of {@link UniRef100 }
     * 
     */
    public UniRef100 createUniRef100() {
        return new UniRef100();
    }

    /**
     * Create an instance of {@link UniRef50 }
     * 
     */
    public UniRef50 createUniRef50() {
        return new UniRef50();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link MemberType.Sequence }
     * 
     */
    public MemberType.Sequence createMemberTypeSequence() {
        return new MemberType.Sequence();
    }

    /**
     * Create an instance of {@link UniRefType }
     * 
     */
    public UniRefType createUniRefType() {
        return new UniRefType();
    }

    /**
     * Create an instance of {@link UniRef90 }
     * 
     */
    public UniRef90 createUniRef90() {
        return new UniRef90();
    }

    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }

    /**
     * Create an instance of {@link MemberType }
     * 
     */
    public MemberType createMemberType() {
        return new MemberType();
    }

}
