//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 08:56:44 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uniprot.org/uniref", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.scripps.yates.annotations.uniref.xml;
