package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AmountType generated by hbm2java
 */
public class AmountType implements java.io.Serializable {

	private String name;
	private Set psmAmounts = new HashSet(0);
	private Set proteinAmounts = new HashSet(0);
	private Set peptideAmounts = new HashSet(0);

	public AmountType() {
	}

	public AmountType(String name) {
		this.name = name;
	}

	public AmountType(String name, Set psmAmounts, Set proteinAmounts,
			Set peptideAmounts) {
		this.name = name;
		this.psmAmounts = psmAmounts;
		this.proteinAmounts = proteinAmounts;
		this.peptideAmounts = peptideAmounts;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getPsmAmounts() {
		return this.psmAmounts;
	}

	public void setPsmAmounts(Set psmAmounts) {
		this.psmAmounts = psmAmounts;
	}

	public Set getProteinAmounts() {
		return this.proteinAmounts;
	}

	public void setProteinAmounts(Set proteinAmounts) {
		this.proteinAmounts = proteinAmounts;
	}

	public Set getPeptideAmounts() {
		return this.peptideAmounts;
	}

	public void setPeptideAmounts(Set peptideAmounts) {
		this.peptideAmounts = peptideAmounts;
	}

}
