package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AnnotationType generated by hbm2java
 */
public class AnnotationType implements java.io.Serializable {

	private String name;
	private Set proteinAnnotations = new HashSet(0);

	public AnnotationType() {
	}

	public AnnotationType(String name) {
		this.name = name;
	}

	public AnnotationType(String name, Set proteinAnnotations) {
		this.name = name;
		this.proteinAnnotations = proteinAnnotations;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getProteinAnnotations() {
		return this.proteinAnnotations;
	}

	public void setProteinAnnotations(Set proteinAnnotations) {
		this.proteinAnnotations = proteinAnnotations;
	}

}
