package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CombinationType generated by hbm2java
 */
public class CombinationType implements java.io.Serializable {

	private String name;
	private String description;
	private Set psmRatioValues = new HashSet(0);
	private Set psmAmounts = new HashSet(0);
	private Set peptideAmounts = new HashSet(0);
	private Set proteinAmounts = new HashSet(0);
	private Set proteinRatioValues = new HashSet(0);
	private Set peptideRatioValues = new HashSet(0);

	public CombinationType() {
	}

	public CombinationType(String name) {
		this.name = name;
	}

	public CombinationType(String name, String description, Set psmRatioValues,
			Set psmAmounts, Set peptideAmounts, Set proteinAmounts,
			Set proteinRatioValues, Set peptideRatioValues) {
		this.name = name;
		this.description = description;
		this.psmRatioValues = psmRatioValues;
		this.psmAmounts = psmAmounts;
		this.peptideAmounts = peptideAmounts;
		this.proteinAmounts = proteinAmounts;
		this.proteinRatioValues = proteinRatioValues;
		this.peptideRatioValues = peptideRatioValues;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getPsmRatioValues() {
		return this.psmRatioValues;
	}

	public void setPsmRatioValues(Set psmRatioValues) {
		this.psmRatioValues = psmRatioValues;
	}

	public Set getPsmAmounts() {
		return this.psmAmounts;
	}

	public void setPsmAmounts(Set psmAmounts) {
		this.psmAmounts = psmAmounts;
	}

	public Set getPeptideAmounts() {
		return this.peptideAmounts;
	}

	public void setPeptideAmounts(Set peptideAmounts) {
		this.peptideAmounts = peptideAmounts;
	}

	public Set getProteinAmounts() {
		return this.proteinAmounts;
	}

	public void setProteinAmounts(Set proteinAmounts) {
		this.proteinAmounts = proteinAmounts;
	}

	public Set getProteinRatioValues() {
		return this.proteinRatioValues;
	}

	public void setProteinRatioValues(Set proteinRatioValues) {
		this.proteinRatioValues = proteinRatioValues;
	}

	public Set getPeptideRatioValues() {
		return this.peptideRatioValues;
	}

	public void setPeptideRatioValues(Set peptideRatioValues) {
		this.peptideRatioValues = peptideRatioValues;
	}

}
