package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ConfidenceScoreType generated by hbm2java
 */
public class ConfidenceScoreType implements java.io.Serializable {

	private String name;
	private String description;
	private Set peptideRatioValues = new HashSet(0);
	private Set psmRatioValues = new HashSet(0);
	private Set proteinScores = new HashSet(0);
	private Set proteinRatioValues = new HashSet(0);
	private Set psmScores = new HashSet(0);
	private Set peptideScores = new HashSet(0);
	private Set ptmSites = new HashSet(0);

	public ConfidenceScoreType() {
	}

	public ConfidenceScoreType(String name) {
		this.name = name;
	}

	public ConfidenceScoreType(String name, String description,
			Set peptideRatioValues, Set psmRatioValues, Set proteinScores,
			Set proteinRatioValues, Set psmScores, Set peptideScores,
			Set ptmSites) {
		this.name = name;
		this.description = description;
		this.peptideRatioValues = peptideRatioValues;
		this.psmRatioValues = psmRatioValues;
		this.proteinScores = proteinScores;
		this.proteinRatioValues = proteinRatioValues;
		this.psmScores = psmScores;
		this.peptideScores = peptideScores;
		this.ptmSites = ptmSites;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getPeptideRatioValues() {
		return this.peptideRatioValues;
	}

	public void setPeptideRatioValues(Set peptideRatioValues) {
		this.peptideRatioValues = peptideRatioValues;
	}

	public Set getPsmRatioValues() {
		return this.psmRatioValues;
	}

	public void setPsmRatioValues(Set psmRatioValues) {
		this.psmRatioValues = psmRatioValues;
	}

	public Set getProteinScores() {
		return this.proteinScores;
	}

	public void setProteinScores(Set proteinScores) {
		this.proteinScores = proteinScores;
	}

	public Set getProteinRatioValues() {
		return this.proteinRatioValues;
	}

	public void setProteinRatioValues(Set proteinRatioValues) {
		this.proteinRatioValues = proteinRatioValues;
	}

	public Set getPsmScores() {
		return this.psmScores;
	}

	public void setPsmScores(Set psmScores) {
		this.psmScores = psmScores;
	}

	public Set getPeptideScores() {
		return this.peptideScores;
	}

	public void setPeptideScores(Set peptideScores) {
		this.peptideScores = peptideScores;
	}

	public Set getPtmSites() {
		return this.ptmSites;
	}

	public void setPtmSites(Set ptmSites) {
		this.ptmSites = ptmSites;
	}

}
