package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Gene generated by hbm2java
 */
public class Gene implements java.io.Serializable {

	private Integer id;
	private String geneId;
	private String geneType;
	private Set proteins = new HashSet(0);

	public Gene() {
	}

	public Gene(String geneId) {
		this.geneId = geneId;
	}

	public Gene(String geneId, String geneType, Set proteins) {
		this.geneId = geneId;
		this.geneType = geneType;
		this.proteins = proteins;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getGeneId() {
		return this.geneId;
	}

	public void setGeneId(String geneId) {
		this.geneId = geneId;
	}

	public String getGeneType() {
		return this.geneType;
	}

	public void setGeneType(String geneType) {
		this.geneType = geneType;
	}

	public Set getProteins() {
		return this.proteins;
	}

	public void setProteins(Set proteins) {
		this.proteins = proteins;
	}

}
