package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Label generated by hbm2java
 */
public class Label implements java.io.Serializable {

	private Integer id;
	private String name;
	private Double massDiff;
	private Set samples = new HashSet(0);

	public Label() {
	}

	public Label(String name) {
		this.name = name;
	}

	public Label(String name, Double massDiff, Set samples) {
		this.name = name;
		this.massDiff = massDiff;
		this.samples = samples;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getMassDiff() {
		return this.massDiff;
	}

	public void setMassDiff(Double massDiff) {
		this.massDiff = massDiff;
	}

	public Set getSamples() {
		return this.samples;
	}

	public void setSamples(Set samples) {
		this.samples = samples;
	}

}
