package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * OperatorType generated by hbm2java
 */
public class OperatorType implements java.io.Serializable {

	private String name;

	public OperatorType() {
	}

	public OperatorType(String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
