package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Organism generated by hbm2java
 */
public class Organism implements java.io.Serializable {

	private String taxonomyId;
	private String name;
	private Set proteins = new HashSet(0);
	private Set samples = new HashSet(0);

	public Organism() {
	}

	public Organism(String taxonomyId) {
		this.taxonomyId = taxonomyId;
	}

	public Organism(String taxonomyId, String name, Set proteins, Set samples) {
		this.taxonomyId = taxonomyId;
		this.name = name;
		this.proteins = proteins;
		this.samples = samples;
	}

	public String getTaxonomyId() {
		return this.taxonomyId;
	}

	public void setTaxonomyId(String taxonomyId) {
		this.taxonomyId = taxonomyId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getProteins() {
		return this.proteins;
	}

	public void setProteins(Set proteins) {
		this.proteins = proteins;
	}

	public Set getSamples() {
		return this.samples;
	}

	public void setSamples(Set samples) {
		this.samples = samples;
	}

}
