package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * PeptideScore generated by hbm2java
 */
public class PeptideScore implements java.io.Serializable {

	private Integer id;
	private ConfidenceScoreType confidenceScoreType;
	private Peptide peptide;
	private String name;
	private double value;

	public PeptideScore() {
	}

	public PeptideScore(ConfidenceScoreType confidenceScoreType,
			Peptide peptide, String name, double value) {
		this.confidenceScoreType = confidenceScoreType;
		this.peptide = peptide;
		this.name = name;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ConfidenceScoreType getConfidenceScoreType() {
		return this.confidenceScoreType;
	}

	public void setConfidenceScoreType(ConfidenceScoreType confidenceScoreType) {
		this.confidenceScoreType = confidenceScoreType;
	}

	public Peptide getPeptide() {
		return this.peptide;
	}

	public void setPeptide(Peptide peptide) {
		this.peptide = peptide;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

}
