package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Peptide generated by hbm2java
 */
public class Peptide implements java.io.Serializable {

	private Integer id;
	private MsRun msRun;
	private String sequence;
	private Set peptideAmounts = new HashSet(0);
	private Set peptideRatioValues = new HashSet(0);
	private Set psms = new HashSet(0);
	private Set conditions = new HashSet(0);
	private Set peptideScores = new HashSet(0);
	private Set proteins = new HashSet(0);

	public Peptide() {
	}

	public Peptide(MsRun msRun, String sequence) {
		this.msRun = msRun;
		this.sequence = sequence;
	}

	public Peptide(MsRun msRun, String sequence, Set peptideAmounts, Set peptideRatioValues, Set psms, Set conditions,
			Set peptideScores, Set proteins) {
		this.msRun = msRun;
		this.sequence = sequence;
		this.peptideAmounts = peptideAmounts;
		this.peptideRatioValues = peptideRatioValues;
		this.psms = psms;
		this.conditions = conditions;
		this.peptideScores = peptideScores;
		this.proteins = proteins;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MsRun getMsRun() {
		return msRun;
	}

	public void setMsRun(MsRun msRun) {
		this.msRun = msRun;
	}

	public String getSequence() {
		return sequence;
	}

	public void setSequence(String sequence) {
		this.sequence = sequence;
	}

	public Set getPeptideAmounts() {
		return peptideAmounts;
	}

	public void setPeptideAmounts(Set peptideAmounts) {
		this.peptideAmounts = peptideAmounts;
	}

	public Set getPeptideRatioValues() {
		return peptideRatioValues;
	}

	public void setPeptideRatioValues(Set peptideRatioValues) {
		this.peptideRatioValues = peptideRatioValues;
	}

	public Set getPsms() {
		return psms;
	}

	public void setPsms(Set psms) {
		this.psms = psms;
	}

	public Set getConditions() {
		return conditions;
	}

	public void setConditions(Set conditions) {
		this.conditions = conditions;
	}

	public Set getPeptideScores() {
		return peptideScores;
	}

	public void setPeptideScores(Set peptideScores) {
		this.peptideScores = peptideScores;
	}

	public Set getProteins() {
		return proteins;
	}

	public void setProteins(Set proteins) {
		this.proteins = proteins;
	}

}
