package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Protein generated by hbm2java
 */

public class Protein implements java.io.Serializable {

	private Integer id;
	private String acc;
	private MsRun msRun;
	private Integer length;
	private Double pi;
	private Double mw;
	private Set psms = new HashSet(0);
	private Set conditions = new HashSet(0);
	private Set proteinRatioValues = new HashSet(0);
	// private Set proteinAccessions = new HashSet(0);
	private Set proteinScores = new HashSet(0);
	private Set proteinAmounts = new HashSet(0);
	private Set proteinThresholds = new HashSet(0);
	private Set proteinAnnotations = new HashSet(0);
	private Set peptides = new HashSet(0);

	public Protein() {
	}

	public Protein(String acc, MsRun msRun) {
		this.acc = acc;
		this.msRun = msRun;
	}

	public Protein(String acc, MsRun msRun, Integer length, Double pi, Double mw, Set psms, Set conditions,
			Set proteinRatioValues,
			// Set proteinAccessions,
			Set proteinScores, Set proteinAmounts, Set proteinThresholds, Set proteinAnnotations, Set peptides) {
		this.acc = acc;
		this.msRun = msRun;
		this.length = length;
		this.pi = pi;
		this.mw = mw;
		this.psms = psms;
		this.conditions = conditions;
		this.proteinRatioValues = proteinRatioValues;
		// this.proteinAccessions = proteinAccessions;
		this.proteinScores = proteinScores;
		this.proteinAmounts = proteinAmounts;
		this.proteinThresholds = proteinThresholds;
		this.proteinAnnotations = proteinAnnotations;
		this.peptides = peptides;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the acc
	 */
	public String getAcc() {
		return acc;
	}

	/**
	 * @param acc
	 *            the acc to set
	 */
	public void setAcc(String acc) {
		this.acc = acc;
	}

	public MsRun getMsRun() {
		return msRun;
	}

	public void setMsRun(MsRun msRun) {
		this.msRun = msRun;
	}

	public Integer getLength() {
		return length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	public Double getPi() {
		return pi;
	}

	public void setPi(Double pi) {
		this.pi = pi;
	}

	public Double getMw() {
		return mw;
	}

	public void setMw(Double mw) {
		this.mw = mw;
	}

	public Set getPsms() {
		return psms;
	}

	public void setPsms(Set psms) {
		this.psms = psms;
	}

	public Set getConditions() {
		return conditions;
	}

	public void setConditions(Set conditions) {
		this.conditions = conditions;
	}

	public Set getProteinRatioValues() {
		return proteinRatioValues;
	}

	public void setProteinRatioValues(Set proteinRatioValues) {
		this.proteinRatioValues = proteinRatioValues;
	}

	// public Set getProteinAccessions() {
	// return proteinAccessions;
	// }
	//
	// public void setProteinAccessions(Set proteinAccessions) {
	// this.proteinAccessions = proteinAccessions;
	// }

	public Set getProteinScores() {
		return proteinScores;
	}

	public void setProteinScores(Set proteinScores) {
		this.proteinScores = proteinScores;
	}

	public Set getProteinAmounts() {
		return proteinAmounts;
	}

	public void setProteinAmounts(Set proteinAmounts) {
		this.proteinAmounts = proteinAmounts;
	}

	public Set getProteinThresholds() {
		return proteinThresholds;
	}

	public void setProteinThresholds(Set proteinThresholds) {
		this.proteinThresholds = proteinThresholds;
	}

	public Set getProteinAnnotations() {
		return proteinAnnotations;
	}

	public void setProteinAnnotations(Set proteinAnnotations) {
		this.proteinAnnotations = proteinAnnotations;
	}

	public Set getPeptides() {
		return peptides;
	}

	public void setPeptides(Set peptides) {
		this.peptides = peptides;
	}

}
