package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProteinAmount generated by hbm2java
 */
public class ProteinAmount implements java.io.Serializable {

	private Integer id;
	private Protein protein;
	private String amountType;
	private Condition condition;
	private String combinationType;
	private double value;
	private Boolean manualSPC;

	public ProteinAmount() {
	}

	public ProteinAmount(Protein protein, String amountType, Condition condition, double value) {
		this.protein = protein;
		this.amountType = amountType;
		this.condition = condition;
		this.value = value;
	}

	public ProteinAmount(Protein protein, String amountType, Condition condition, String combinationType,
			double value) {
		this.protein = protein;
		this.amountType = amountType;
		this.condition = condition;
		this.combinationType = combinationType;
		this.value = value;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Protein getProtein() {
		return protein;
	}

	public void setProtein(Protein protein) {
		this.protein = protein;
	}

	public String getAmountType() {
		return amountType;
	}

	public void setAmountType(String amountType) {
		this.amountType = amountType;
	}

	public Condition getCondition() {
		return condition;
	}

	public void setCondition(Condition condition) {
		this.condition = condition;
	}

	public String getCombinationType() {
		return combinationType;
	}

	public void setCombinationType(String combinationType) {
		this.combinationType = combinationType;
	}

	public double getValue() {
		return value;
	}

	public void setValue(double value) {
		this.value = value;
	}

	/**
	 * @return the manualSPC
	 */
	public Boolean getManualSPC() {
		return manualSPC;
	}

	/**
	 * @param manualSPC the manualSPC to set
	 */
	public void setManualSPC(Boolean manualSPC) {
		this.manualSPC = manualSPC;
	}

}
