package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProteinThreshold generated by hbm2java
 */
public class ProteinThreshold implements java.io.Serializable {

	private Integer id;
	private Protein protein;
	private boolean passThreshold;
	private String name;
	private String description;

	public ProteinThreshold() {
	}

	public ProteinThreshold(Protein protein, boolean passThreshold, String name, String description) {
		this.protein = protein;
		this.passThreshold = passThreshold;
		this.name = name;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Protein getProtein() {
		return this.protein;
	}

	public void setProtein(Protein protein) {
		this.protein = protein;
	}

	public boolean isPassThreshold() {
		return this.passThreshold;
	}

	public void setPassThreshold(boolean passThreshold) {
		this.passThreshold = passThreshold;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
