package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProteinAnnotation generated by hbm2java
 */
public class ProteinAnnotation implements java.io.Serializable {

	private Integer id;
	private AnnotationType annotationType;
	private Protein protein;
	private String name;
	private String value;
	private String source;

	public ProteinAnnotation() {
	}

	public ProteinAnnotation(AnnotationType annotationType, Protein protein,
			String name) {
		this.annotationType = annotationType;
		this.protein = protein;
		this.name = name;
	}

	public ProteinAnnotation(AnnotationType annotationType, Protein protein,
			String name, String value, String source) {
		this.annotationType = annotationType;
		this.protein = protein;
		this.name = name;
		this.value = value;
		this.source = source;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public AnnotationType getAnnotationType() {
		return this.annotationType;
	}

	public void setAnnotationType(AnnotationType annotationType) {
		this.annotationType = annotationType;
	}

	public Protein getProtein() {
		return this.protein;
	}

	public void setProtein(Protein protein) {
		this.protein = protein;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

}
