package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProteinRatioValue generated by hbm2java
 */
public class ProteinRatioValue implements java.io.Serializable {

	private Integer id;
	private String confidenceScoreType;
	private Protein protein;
	private String combinationType;
	private RatioDescriptor ratioDescriptor;
	private double value;
	private Double confidenceScoreValue;
	private String confidenceScoreName;

	public ProteinRatioValue() {
	}

	public ProteinRatioValue(Protein protein, RatioDescriptor ratioDescriptor, double value) {
		this.protein = protein;
		this.ratioDescriptor = ratioDescriptor;
		this.value = value;
	}

	public ProteinRatioValue(String confidenceScoreType, Protein protein, String combinationType,
			RatioDescriptor ratioDescriptor, double value, Double confidenceScoreValue, String confidenceScoreName) {
		this.confidenceScoreType = confidenceScoreType;
		this.protein = protein;
		this.combinationType = combinationType;
		this.ratioDescriptor = ratioDescriptor;
		this.value = value;
		this.confidenceScoreValue = confidenceScoreValue;
		this.confidenceScoreName = confidenceScoreName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getConfidenceScoreType() {
		return this.confidenceScoreType;
	}

	public void setConfidenceScoreType(String confidenceScoreType) {
		this.confidenceScoreType = confidenceScoreType;
	}

	public Protein getProtein() {
		return this.protein;
	}

	public void setProtein(Protein protein) {
		this.protein = protein;
	}

	public String getCombinationType() {
		return this.combinationType;
	}

	public void setCombinationType(String combinationType) {
		this.combinationType = combinationType;
	}

	public RatioDescriptor getRatioDescriptor() {
		return this.ratioDescriptor;
	}

	public void setRatioDescriptor(RatioDescriptor ratioDescriptor) {
		this.ratioDescriptor = ratioDescriptor;
	}

	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

	public Double getConfidenceScoreValue() {
		return this.confidenceScoreValue;
	}

	public void setConfidenceScoreValue(Double confidenceScoreValue) {
		this.confidenceScoreValue = confidenceScoreValue;
	}

	public String getConfidenceScoreName() {
		return this.confidenceScoreName;
	}

	public void setConfidenceScoreName(String confidenceScoreName) {
		this.confidenceScoreName = confidenceScoreName;
	}

}
