package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Psm generated by hbm2java
 */
public class Psm implements java.io.Serializable {

	private Integer id;
	private MsRun msRun;
	private Peptide peptide;
	private String psmId;
	private Double mh;
	private Double calMh;
	private Double totalIntensity;
	private Double ppmError;
	private Integer spr;
	private Double ionProportion;
	private Double pi;
	private String sequence;
	private String fullSequence;
	private String beforeSeq;
	private String afterSeq;
	private String chargeState;
	private Set psmScores = new HashSet(0);
	private Set psmAmounts = new HashSet(0);
	private Set ptms = new HashSet(0);
	private Set conditions = new HashSet(0);
	private Set proteins = new HashSet(0);
	private Set psmRatioValues = new HashSet(0);

	public Psm() {
	}

	public Psm(MsRun msRun, Peptide peptide, String sequence,
			String fullSequence) {
		this.msRun = msRun;
		this.peptide = peptide;
		this.sequence = sequence;
		this.fullSequence = fullSequence;
	}

	public Psm(MsRun msRun, Peptide peptide, String psmId, Double mh,
			Double calMh, Double totalIntensity, Double ppmError, Integer spr,
			Double ionProportion, Double pi, String sequence,
			String fullSequence, String beforeSeq, String afterSeq,
			String chargeState, Set psmScores, Set psmAmounts, Set ptms,
			Set conditions, Set proteins, Set psmRatioValues) {
		this.msRun = msRun;
		this.peptide = peptide;
		this.psmId = psmId;
		this.mh = mh;
		this.calMh = calMh;
		this.totalIntensity = totalIntensity;
		this.ppmError = ppmError;
		this.spr = spr;
		this.ionProportion = ionProportion;
		this.pi = pi;
		this.sequence = sequence;
		this.fullSequence = fullSequence;
		this.beforeSeq = beforeSeq;
		this.afterSeq = afterSeq;
		this.chargeState = chargeState;
		this.psmScores = psmScores;
		this.psmAmounts = psmAmounts;
		this.ptms = ptms;
		this.conditions = conditions;
		this.proteins = proteins;
		this.psmRatioValues = psmRatioValues;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MsRun getMsRun() {
		return this.msRun;
	}

	public void setMsRun(MsRun msRun) {
		this.msRun = msRun;
	}

	public Peptide getPeptide() {
		return this.peptide;
	}

	public void setPeptide(Peptide peptide) {
		this.peptide = peptide;
	}

	public String getPsmId() {
		return this.psmId;
	}

	public void setPsmId(String psmId) {
		this.psmId = psmId;
	}

	public Double getMh() {
		return this.mh;
	}

	public void setMh(Double mh) {
		this.mh = mh;
	}

	public Double getCalMh() {
		return this.calMh;
	}

	public void setCalMh(Double calMh) {
		this.calMh = calMh;
	}

	public Double getTotalIntensity() {
		return this.totalIntensity;
	}

	public void setTotalIntensity(Double totalIntensity) {
		this.totalIntensity = totalIntensity;
	}

	public Double getPpmError() {
		return this.ppmError;
	}

	public void setPpmError(Double ppmError) {
		this.ppmError = ppmError;
	}

	public Integer getSpr() {
		return this.spr;
	}

	public void setSpr(Integer spr) {
		this.spr = spr;
	}

	public Double getIonProportion() {
		return this.ionProportion;
	}

	public void setIonProportion(Double ionProportion) {
		this.ionProportion = ionProportion;
	}

	public Double getPi() {
		return this.pi;
	}

	public void setPi(Double pi) {
		this.pi = pi;
	}

	public String getSequence() {
		return this.sequence;
	}

	public void setSequence(String sequence) {
		this.sequence = sequence;
	}

	public String getFullSequence() {
		return this.fullSequence;
	}

	public void setFullSequence(String fullSequence) {
		this.fullSequence = fullSequence;
	}

	public String getBeforeSeq() {
		return this.beforeSeq;
	}

	public void setBeforeSeq(String beforeSeq) {
		this.beforeSeq = beforeSeq;
	}

	public String getAfterSeq() {
		return this.afterSeq;
	}

	public void setAfterSeq(String afterSeq) {
		this.afterSeq = afterSeq;
	}

	public String getChargeState() {
		return this.chargeState;
	}

	public void setChargeState(String chargeState) {
		this.chargeState = chargeState;
	}

	public Set getPsmScores() {
		return this.psmScores;
	}

	public void setPsmScores(Set psmScores) {
		this.psmScores = psmScores;
	}

	public Set getPsmAmounts() {
		return this.psmAmounts;
	}

	public void setPsmAmounts(Set psmAmounts) {
		this.psmAmounts = psmAmounts;
	}

	public Set getPtms() {
		return this.ptms;
	}

	public void setPtms(Set ptms) {
		this.ptms = ptms;
	}

	public Set getConditions() {
		return this.conditions;
	}

	public void setConditions(Set conditions) {
		this.conditions = conditions;
	}

	public Set getProteins() {
		return this.proteins;
	}

	public void setProteins(Set proteins) {
		this.proteins = proteins;
	}

	public Set getPsmRatioValues() {
		return this.psmRatioValues;
	}

	public void setPsmRatioValues(Set psmRatioValues) {
		this.psmRatioValues = psmRatioValues;
	}

}
