package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * PsmAmount generated by hbm2java
 */
public class PsmAmount implements java.io.Serializable {

	private Integer id;
	private String amountType;
	private Condition condition;
	private String combinationType;
	private Psm psm;
	private double value;
	private Boolean singleton;

	public PsmAmount() {
	}

	public PsmAmount(String amountType, Condition condition, Psm psm, double value) {
		this.amountType = amountType;
		this.condition = condition;
		this.psm = psm;
		this.value = value;
	}

	public PsmAmount(String amountType, Condition condition, String combinationType, Psm psm, double value,
			Boolean singleton) {
		this.amountType = amountType;
		this.condition = condition;
		this.combinationType = combinationType;
		this.psm = psm;
		this.value = value;
		this.singleton = singleton;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAmountType() {
		return this.amountType;
	}

	public void setAmountType(String amountType) {
		this.amountType = amountType;
	}

	public Condition getCondition() {
		return this.condition;
	}

	public void setCondition(Condition condition) {
		this.condition = condition;
	}

	public String getCombinationType() {
		return this.combinationType;
	}

	public void setCombinationType(String combinationType) {
		this.combinationType = combinationType;
	}

	public Psm getPsm() {
		return this.psm;
	}

	public void setPsm(Psm psm) {
		this.psm = psm;
	}

	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

	public Boolean getSingleton() {
		return this.singleton;
	}

	public void setSingleton(Boolean singleton) {
		this.singleton = singleton;
	}

}
