package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * PsmRatioValue generated by hbm2java
 */
public class PsmRatioValue implements java.io.Serializable {

	private Integer id;
	private String confidenceScoreType;
	private String combinationType;
	private RatioDescriptor ratioDescriptor;
	private Psm psm;
	private double value;
	private Double confidenceScoreValue;
	private String confidenceScoreName;

	public PsmRatioValue() {
	}

	public PsmRatioValue(RatioDescriptor ratioDescriptor, Psm psm, double value) {
		this.ratioDescriptor = ratioDescriptor;
		this.psm = psm;
		this.value = value;
	}

	public PsmRatioValue(String confidenceScoreType, String combinationType, RatioDescriptor ratioDescriptor, Psm psm,
			double value, Double confidenceScoreValue, String confidenceScoreName) {
		this.confidenceScoreType = confidenceScoreType;
		this.combinationType = combinationType;
		this.ratioDescriptor = ratioDescriptor;
		this.psm = psm;
		this.value = value;
		this.confidenceScoreValue = confidenceScoreValue;
		this.confidenceScoreName = confidenceScoreName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getConfidenceScoreType() {
		return this.confidenceScoreType;
	}

	public void setConfidenceScoreType(String confidenceScoreType) {
		this.confidenceScoreType = confidenceScoreType;
	}

	public String getCombinationType() {
		return this.combinationType;
	}

	public void setCombinationType(String combinationType) {
		this.combinationType = combinationType;
	}

	public RatioDescriptor getRatioDescriptor() {
		return this.ratioDescriptor;
	}

	public void setRatioDescriptor(RatioDescriptor ratioDescriptor) {
		this.ratioDescriptor = ratioDescriptor;
	}

	public Psm getPsm() {
		return this.psm;
	}

	public void setPsm(Psm psm) {
		this.psm = psm;
	}

	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

	public Double getConfidenceScoreValue() {
		return this.confidenceScoreValue;
	}

	public void setConfidenceScoreValue(Double confidenceScoreValue) {
		this.confidenceScoreValue = confidenceScoreValue;
	}

	public String getConfidenceScoreName() {
		return this.confidenceScoreName;
	}

	public void setConfidenceScoreName(String confidenceScoreName) {
		this.confidenceScoreName = confidenceScoreName;
	}

}
