package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Ptm generated by hbm2java
 */
public class Ptm implements java.io.Serializable {

	private Integer id;
	private Psm psm;
	private Peptide peptide;
	private double massShift;
	private String name;
	private String cvId;
	private Set ptmSites = new HashSet(0);

	public Ptm() {
	}

	public Ptm(Psm psm, double massShift, String name) {
		this.psm = psm;
		this.massShift = massShift;
		this.name = name;
	}

	public Ptm(Psm psm, double massShift, String name, String cvId, Set ptmSites) {
		this.psm = psm;
		this.massShift = massShift;
		this.name = name;
		this.cvId = cvId;
		this.ptmSites = ptmSites;
	}

	public Ptm(Peptide peptide, double massShift, String name) {
		this.peptide = peptide;
		this.massShift = massShift;
		this.name = name;
	}

	public Ptm(Peptide peptide, double massShift, String name, String cvId, Set ptmSites) {
		this.peptide = peptide;
		this.massShift = massShift;
		this.name = name;
		this.cvId = cvId;
		this.ptmSites = ptmSites;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Psm getPsm() {
		return psm;
	}

	public Peptide getPeptide() {
		return peptide;
	}

	public void setPeptide(Peptide peptide) {
		this.peptide = peptide;
	}

	public void setPsm(Psm psm) {
		this.psm = psm;
	}

	public double getMassShift() {
		return massShift;
	}

	public void setMassShift(double massShift) {
		this.massShift = massShift;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCvId() {
		return cvId;
	}

	public void setCvId(String cvId) {
		this.cvId = cvId;
	}

	public Set getPtmSites() {
		return ptmSites;
	}

	public void setPtmSites(Set ptmSites) {
		this.ptmSites = ptmSites;
	}

}
