package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * PtmSite generated by hbm2java
 */
public class PtmSite implements java.io.Serializable {

	private Integer id;
	private String confidenceScoreType;
	private Ptm ptm;
	private String aa;
	private int position;
	private String confidenceScoreValue;
	private String confidenceScoreName;

	public PtmSite() {
	}

	public PtmSite(Ptm ptm, String aa, int position) {
		this.ptm = ptm;
		this.aa = aa;
		this.position = position;
	}

	public PtmSite(String confidenceScoreType, Ptm ptm, String aa, int position, String confidenceScoreValue,
			String confidenceScoreName) {
		this.confidenceScoreType = confidenceScoreType;
		this.ptm = ptm;
		this.aa = aa;
		this.position = position;
		this.confidenceScoreValue = confidenceScoreValue;
		this.confidenceScoreName = confidenceScoreName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getConfidenceScoreType() {
		return this.confidenceScoreType;
	}

	public void setConfidenceScoreType(String confidenceScoreType) {
		this.confidenceScoreType = confidenceScoreType;
	}

	public Ptm getPtm() {
		return this.ptm;
	}

	public void setPtm(Ptm ptm) {
		this.ptm = ptm;
	}

	public String getAa() {
		return this.aa;
	}

	public void setAa(String aa) {
		this.aa = aa;
	}

	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	public String getConfidenceScoreValue() {
		return this.confidenceScoreValue;
	}

	public void setConfidenceScoreValue(String confidenceScoreValue) {
		this.confidenceScoreValue = confidenceScoreValue;
	}

	public String getConfidenceScoreName() {
		return this.confidenceScoreName;
	}

	public void setConfidenceScoreName(String confidenceScoreName) {
		this.confidenceScoreName = confidenceScoreName;
	}

}
