package edu.scripps.yates.proteindb.persistence.mysql;

// Generated Feb 24, 2015 2:42:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tissue generated by hbm2java
 */
public class Tissue implements java.io.Serializable {

	private String tissueId;
	private String name;
	private Set samples = new HashSet(0);

	public Tissue() {
	}

	public Tissue(String tissueId) {
		this.tissueId = tissueId;
	}

	public Tissue(String tissueId, String name, Set samples) {
		this.tissueId = tissueId;
		this.name = name;
		this.samples = samples;
	}

	public String getTissueId() {
		return this.tissueId;
	}

	public void setTissueId(String tissueId) {
		this.tissueId = tissueId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getSamples() {
		return this.samples;
	}

	public void setSamples(Set samples) {
		this.samples = samples;
	}

}
