//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.03 at 05:46:13 PM PDT 
//


package edu.scripps.yates.panther.overrepresentation.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.scripps.yates.panther.overrepresentation.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.scripps.yates.panther.overrepresentation.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Overrepresentation }
     * 
     */
    public Overrepresentation createOverrepresentation() {
        return new Overrepresentation();
    }

    /**
     * Create an instance of {@link Overrepresentation.Group.Result }
     * 
     */
    public Overrepresentation.Group.Result createOverrepresentationGroupResult() {
        return new Overrepresentation.Group.Result();
    }

    /**
     * Create an instance of {@link Overrepresentation.Group.Result.Term }
     * 
     */
    public Overrepresentation.Group.Result.Term createOverrepresentationGroupResultTerm() {
        return new Overrepresentation.Group.Result.Term();
    }

    /**
     * Create an instance of {@link Overrepresentation.Group.Result.InputList.MappedIdList }
     * 
     */
    public Overrepresentation.Group.Result.InputList.MappedIdList createOverrepresentationGroupResultInputListMappedIdList() {
        return new Overrepresentation.Group.Result.InputList.MappedIdList();
    }

    /**
     * Create an instance of {@link Overrepresentation.UploadLists.InputList }
     * 
     */
    public Overrepresentation.UploadLists.InputList createOverrepresentationUploadListsInputList() {
        return new Overrepresentation.UploadLists.InputList();
    }

    /**
     * Create an instance of {@link Overrepresentation.UploadLists }
     * 
     */
    public Overrepresentation.UploadLists createOverrepresentationUploadLists() {
        return new Overrepresentation.UploadLists();
    }

    /**
     * Create an instance of {@link Overrepresentation.Group }
     * 
     */
    public Overrepresentation.Group createOverrepresentationGroup() {
        return new Overrepresentation.Group();
    }

    /**
     * Create an instance of {@link Overrepresentation.Group.Result.InputList }
     * 
     */
    public Overrepresentation.Group.Result.InputList createOverrepresentationGroupResultInputList() {
        return new Overrepresentation.Group.Result.InputList();
    }

}
