//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.03 at 05:46:13 PM PDT 
//


package edu.scripps.yates.panther.overrepresentation.xml;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="test_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="annotation_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tool_release_date" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="data_version_release_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="correction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reference" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="upload_lists">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="input_list">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="list_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="organism" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="group" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="result" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="term">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *                                       &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="number_in_reference" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                             &lt;element name="input_list">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="list_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="number_in_list" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                       &lt;element name="expected" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                       &lt;element name="plus_minus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="pValue" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="fold_enrichment" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                       &lt;element name="fdr" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="mapped_id_list" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="mapped_id" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testType",
    "annotationType",
    "toolReleaseDate",
    "dataVersionReleaseDate",
    "correction",
    "reference",
    "uploadLists",
    "group"
})
@XmlRootElement(name = "overrepresentation")
public class Overrepresentation {

    @XmlElement(name = "test_type", required = true)
    protected String testType;
    @XmlElement(name = "annotation_type", required = true)
    protected String annotationType;
    @XmlElement(name = "tool_release_date")
    @XmlSchemaType(name = "unsignedInt")
    protected long toolReleaseDate;
    @XmlElement(name = "data_version_release_date", required = true)
    protected String dataVersionReleaseDate;
    @XmlElement(required = true)
    protected String correction;
    @XmlElement(required = true)
    protected Object reference;
    @XmlElement(name = "upload_lists", required = true)
    protected Overrepresentation.UploadLists uploadLists;
    @XmlElement(required = true)
    protected List<Overrepresentation.Group> group;

    /**
     * Gets the value of the testType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestType() {
        return testType;
    }

    /**
     * Sets the value of the testType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestType(String value) {
        this.testType = value;
    }

    /**
     * Gets the value of the annotationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnotationType() {
        return annotationType;
    }

    /**
     * Sets the value of the annotationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnotationType(String value) {
        this.annotationType = value;
    }

    /**
     * Gets the value of the toolReleaseDate property.
     * 
     */
    public long getToolReleaseDate() {
        return toolReleaseDate;
    }

    /**
     * Sets the value of the toolReleaseDate property.
     * 
     */
    public void setToolReleaseDate(long value) {
        this.toolReleaseDate = value;
    }

    /**
     * Gets the value of the dataVersionReleaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataVersionReleaseDate() {
        return dataVersionReleaseDate;
    }

    /**
     * Sets the value of the dataVersionReleaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataVersionReleaseDate(String value) {
        this.dataVersionReleaseDate = value;
    }

    /**
     * Gets the value of the correction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrection() {
        return correction;
    }

    /**
     * Sets the value of the correction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrection(String value) {
        this.correction = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setReference(Object value) {
        this.reference = value;
    }

    /**
     * Gets the value of the uploadLists property.
     * 
     * @return
     *     possible object is
     *     {@link Overrepresentation.UploadLists }
     *     
     */
    public Overrepresentation.UploadLists getUploadLists() {
        return uploadLists;
    }

    /**
     * Sets the value of the uploadLists property.
     * 
     * @param value
     *     allowed object is
     *     {@link Overrepresentation.UploadLists }
     *     
     */
    public void setUploadLists(Overrepresentation.UploadLists value) {
        this.uploadLists = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the group property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Overrepresentation.Group }
     * 
     * 
     */
    public List<Overrepresentation.Group> getGroup() {
        if (group == null) {
            group = new ArrayList<Overrepresentation.Group>();
        }
        return this.group;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="result" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="term">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
     *                             &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="number_in_reference" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *                   &lt;element name="input_list">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="list_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="number_in_list" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                             &lt;element name="expected" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                             &lt;element name="plus_minus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="pValue" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                             &lt;element name="fold_enrichment" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                             &lt;element name="fdr" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                             &lt;element name="mapped_id_list" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="mapped_id" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class Group {

        @XmlElement(required = true)
        protected List<Overrepresentation.Group.Result> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Overrepresentation.Group.Result }
         * 
         * 
         */
        public List<Overrepresentation.Group.Result> getResult() {
            if (result == null) {
                result = new ArrayList<Overrepresentation.Group.Result>();
            }
            return this.result;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="term">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
         *                   &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="number_in_reference" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
         *         &lt;element name="input_list">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="list_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="number_in_list" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                   &lt;element name="expected" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                   &lt;element name="plus_minus" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="pValue" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                   &lt;element name="fold_enrichment" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                   &lt;element name="fdr" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                   &lt;element name="mapped_id_list" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="mapped_id" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "term",
            "numberInReference",
            "inputList"
        })
        public static class Result {

            @XmlElement(required = true)
            protected Overrepresentation.Group.Result.Term term;
            @XmlElement(name = "number_in_reference")
            @XmlSchemaType(name = "unsignedShort")
            protected int numberInReference;
            @XmlElement(name = "input_list", required = true)
            protected Overrepresentation.Group.Result.InputList inputList;

            /**
             * Gets the value of the term property.
             * 
             * @return
             *     possible object is
             *     {@link Overrepresentation.Group.Result.Term }
             *     
             */
            public Overrepresentation.Group.Result.Term getTerm() {
                return term;
            }

            /**
             * Sets the value of the term property.
             * 
             * @param value
             *     allowed object is
             *     {@link Overrepresentation.Group.Result.Term }
             *     
             */
            public void setTerm(Overrepresentation.Group.Result.Term value) {
                this.term = value;
            }

            /**
             * Gets the value of the numberInReference property.
             * 
             */
            public int getNumberInReference() {
                return numberInReference;
            }

            /**
             * Sets the value of the numberInReference property.
             * 
             */
            public void setNumberInReference(int value) {
                this.numberInReference = value;
            }

            /**
             * Gets the value of the inputList property.
             * 
             * @return
             *     possible object is
             *     {@link Overrepresentation.Group.Result.InputList }
             *     
             */
            public Overrepresentation.Group.Result.InputList getInputList() {
                return inputList;
            }

            /**
             * Sets the value of the inputList property.
             * 
             * @param value
             *     allowed object is
             *     {@link Overrepresentation.Group.Result.InputList }
             *     
             */
            public void setInputList(Overrepresentation.Group.Result.InputList value) {
                this.inputList = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="list_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="number_in_list" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *         &lt;element name="expected" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *         &lt;element name="plus_minus" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="pValue" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *         &lt;element name="fold_enrichment" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *         &lt;element name="fdr" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *         &lt;element name="mapped_id_list" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="mapped_id" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "listName",
                "numberInList",
                "expected",
                "plusMinus",
                "pValue",
                "foldEnrichment",
                "fdr",
                "mappedIdList"
            })
            public static class InputList {

                @XmlElement(name = "list_name", required = true)
                protected String listName;
                @XmlElement(name = "number_in_list")
                @XmlSchemaType(name = "unsignedByte")
                protected short numberInList;
                @XmlElement(required = true)
                protected BigDecimal expected;
                @XmlElement(name = "plus_minus", required = true)
                protected String plusMinus;
                protected double pValue;
                @XmlElement(name = "fold_enrichment", required = true)
                protected BigDecimal foldEnrichment;
                protected double fdr;
                @XmlElement(name = "mapped_id_list")
                protected Overrepresentation.Group.Result.InputList.MappedIdList mappedIdList;

                /**
                 * Gets the value of the listName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getListName() {
                    return listName;
                }

                /**
                 * Sets the value of the listName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setListName(String value) {
                    this.listName = value;
                }

                /**
                 * Gets the value of the numberInList property.
                 * 
                 */
                public short getNumberInList() {
                    return numberInList;
                }

                /**
                 * Sets the value of the numberInList property.
                 * 
                 */
                public void setNumberInList(short value) {
                    this.numberInList = value;
                }

                /**
                 * Gets the value of the expected property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getExpected() {
                    return expected;
                }

                /**
                 * Sets the value of the expected property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setExpected(BigDecimal value) {
                    this.expected = value;
                }

                /**
                 * Gets the value of the plusMinus property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPlusMinus() {
                    return plusMinus;
                }

                /**
                 * Sets the value of the plusMinus property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPlusMinus(String value) {
                    this.plusMinus = value;
                }

                /**
                 * Gets the value of the pValue property.
                 * 
                 */
                public double getPValue() {
                    return pValue;
                }

                /**
                 * Sets the value of the pValue property.
                 * 
                 */
                public void setPValue(double value) {
                    this.pValue = value;
                }

                /**
                 * Gets the value of the foldEnrichment property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getFoldEnrichment() {
                    return foldEnrichment;
                }

                /**
                 * Sets the value of the foldEnrichment property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setFoldEnrichment(BigDecimal value) {
                    this.foldEnrichment = value;
                }

                /**
                 * Gets the value of the fdr property.
                 * 
                 */
                public double getFdr() {
                    return fdr;
                }

                /**
                 * Sets the value of the fdr property.
                 * 
                 */
                public void setFdr(double value) {
                    this.fdr = value;
                }

                /**
                 * Gets the value of the mappedIdList property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Overrepresentation.Group.Result.InputList.MappedIdList }
                 *     
                 */
                public Overrepresentation.Group.Result.InputList.MappedIdList getMappedIdList() {
                    return mappedIdList;
                }

                /**
                 * Sets the value of the mappedIdList property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Overrepresentation.Group.Result.InputList.MappedIdList }
                 *     
                 */
                public void setMappedIdList(Overrepresentation.Group.Result.InputList.MappedIdList value) {
                    this.mappedIdList = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="mapped_id" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "mappedId"
                })
                public static class MappedIdList {

                    @XmlElement(name = "mapped_id", required = true)
                    protected List<String> mappedId;

                    /**
                     * Gets the value of the mappedId property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the mappedId property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getMappedId().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link String }
                     * 
                     * 
                     */
                    public List<String> getMappedId() {
                        if (mappedId == null) {
                            mappedId = new ArrayList<String>();
                        }
                        return this.mappedId;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
             *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id",
                "level",
                "label"
            })
            public static class Term {

                protected String id;
                @XmlSchemaType(name = "unsignedByte")
                protected Short level;
                @XmlElement(required = true)
                protected String label;

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setId(String value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the level property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Short }
                 *     
                 */
                public Short getLevel() {
                    return level;
                }

                /**
                 * Sets the value of the level property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Short }
                 *     
                 */
                public void setLevel(Short value) {
                    this.level = value;
                }

                /**
                 * Gets the value of the label property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLabel() {
                    return label;
                }

                /**
                 * Sets the value of the label property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLabel(String value) {
                    this.label = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="input_list">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="list_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="organism" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "inputList"
    })
    public static class UploadLists {

        @XmlElement(name = "input_list", required = true)
        protected Overrepresentation.UploadLists.InputList inputList;

        /**
         * Gets the value of the inputList property.
         * 
         * @return
         *     possible object is
         *     {@link Overrepresentation.UploadLists.InputList }
         *     
         */
        public Overrepresentation.UploadLists.InputList getInputList() {
            return inputList;
        }

        /**
         * Sets the value of the inputList property.
         * 
         * @param value
         *     allowed object is
         *     {@link Overrepresentation.UploadLists.InputList }
         *     
         */
        public void setInputList(Overrepresentation.UploadLists.InputList value) {
            this.inputList = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="list_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="organism" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "listName",
            "organism"
        })
        public static class InputList {

            @XmlElement(name = "list_name", required = true)
            protected String listName;
            @XmlElement(required = true)
            protected String organism;

            /**
             * Gets the value of the listName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getListName() {
                return listName;
            }

            /**
             * Sets the value of the listName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setListName(String value) {
                this.listName = value;
            }

            /**
             * Gets the value of the organism property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrganism() {
                return organism;
            }

            /**
             * Sets the value of the organism property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrganism(String value) {
                this.organism = value;
            }

        }

    }

}
