//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.25 at 04:59:40 PM PDT 
//


package edu.scripps.yates.census.quant.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for redundant_protein_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="redundant_protein_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="locus" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="seq_ct" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="spec_ct" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="seq_cov" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="molwt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pi" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="val" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "redundant_protein_type")
public class RedundantProteinType {

    @XmlAttribute(name = "locus")
    protected String locus;
    @XmlAttribute(name = "seq_ct")
    protected Integer seqCt;
    @XmlAttribute(name = "spec_ct")
    protected Integer specCt;
    @XmlAttribute(name = "seq_cov")
    protected String seqCov;
    @XmlAttribute(name = "length")
    protected String length;
    @XmlAttribute(name = "molwt")
    protected String molwt;
    @XmlAttribute(name = "pi")
    protected String pi;
    @XmlAttribute(name = "val")
    protected String val;
    @XmlAttribute(name = "desc")
    protected String desc;

    /**
     * Gets the value of the locus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocus() {
        return locus;
    }

    /**
     * Sets the value of the locus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocus(String value) {
        this.locus = value;
    }

    /**
     * Gets the value of the seqCt property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSeqCt() {
        return seqCt;
    }

    /**
     * Sets the value of the seqCt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSeqCt(Integer value) {
        this.seqCt = value;
    }

    /**
     * Gets the value of the specCt property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSpecCt() {
        return specCt;
    }

    /**
     * Sets the value of the specCt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSpecCt(Integer value) {
        this.specCt = value;
    }

    /**
     * Gets the value of the seqCov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeqCov() {
        return seqCov;
    }

    /**
     * Sets the value of the seqCov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqCov(String value) {
        this.seqCov = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLength(String value) {
        this.length = value;
    }

    /**
     * Gets the value of the molwt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMolwt() {
        return molwt;
    }

    /**
     * Sets the value of the molwt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMolwt(String value) {
        this.molwt = value;
    }

    /**
     * Gets the value of the pi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPi() {
        return pi;
    }

    /**
     * Sets the value of the pi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPi(String value) {
        this.pi = value;
    }

    /**
     * Gets the value of the val property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVal() {
        return val;
    }

    /**
     * Sets the value of the val property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVal(String value) {
        this.val = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

}
