//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.12.03 at 06:58:04 PM PST
//

package edu.scripps.yates.shared.model.projectCreator.excel;

import java.io.Serializable;

import edu.scripps.yates.shared.model.AmountType;

public class AmountTypeBean implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -3449508206508887956L;
	protected AmountCombinationTypeBean combinationType;
	protected AmountType type;
	protected String columnRef;

	/**
	 * Gets the value of the combinationType property.
	 *
	 * @return possible object is {@link AmountCombinationTypeBean }
	 *
	 */
	public AmountCombinationTypeBean getCombinationType() {
		return combinationType;
	}

	/**
	 * Sets the value of the combinationType property.
	 *
	 * @param value
	 *            allowed object is {@link AmountCombinationTypeBean }
	 *
	 */
	public void setCombinationType(AmountCombinationTypeBean value) {
		combinationType = value;
	}

	/**
	 * Gets the value of the type property.
	 *
	 * @return possible object is {@link AmountType }
	 *
	 */
	public AmountType getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 *
	 * @param value
	 *            allowed object is {@link AmountType }
	 *
	 */
	public void setType(AmountType value) {
		type = value;
	}

	/**
	 * Gets the value of the columnRef property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getColumnRef() {
		return columnRef;
	}

	/**
	 * Sets the value of the columnRef property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setColumnRef(String value) {
		columnRef = value;
	}

}
