//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.12.03 at 06:58:04 PM PST
//

package edu.scripps.yates.shared.model.projectCreator.excel;

import java.io.Serializable;

public class ColumnTypeBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 235689768236178429L;
	protected String id;
	protected String header;
	protected boolean number;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		id = value;
	}

	/**
	 * Gets the value of the header property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHeader() {
		return header;
	}

	/**
	 * Sets the value of the header property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHeader(String value) {
		header = value;
	}

	/**
	 * Gets the value of the number property.
	 * 
	 */
	public boolean isNumber() {
		return number;
	}

	/**
	 * Sets the value of the number property.
	 * 
	 */
	public void setNumber(boolean value) {
		number = value;
	}

}
