//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.12.03 at 06:58:04 PM PST
//

package edu.scripps.yates.shared.model.projectCreator.excel;

import java.io.Serializable;

import edu.scripps.yates.client.gui.components.projectCreatorWizard.manager.HasId;

public class ExperimentalConditionTypeBean implements Serializable, HasId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8733798005933824628L;
	protected String description;
	protected IdentificationInfoTypeBean identificationInfo;
	protected QuantificationInfoTypeBean quantificationInfo;
	protected String id;
	protected String sampleRef;

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		description = value;
	}

	/**
	 * Gets the value of the identificationInfo property.
	 * 
	 * @return possible object is {@link IdentificationInfoTypeBean }
	 * 
	 */
	public IdentificationInfoTypeBean getIdentificationInfo() {
		return identificationInfo;
	}

	/**
	 * Sets the value of the identificationInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link IdentificationInfoTypeBean }
	 * 
	 */
	public void setIdentificationInfo(IdentificationInfoTypeBean value) {
		identificationInfo = value;
	}

	/**
	 * Gets the value of the quantificationInfo property.
	 * 
	 * @return possible object is {@link QuantificationInfoTypeBean }
	 * 
	 */
	public QuantificationInfoTypeBean getQuantificationInfo() {
		return quantificationInfo;
	}

	/**
	 * Sets the value of the quantificationInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantificationInfoTypeBean }
	 * 
	 */
	public void setQuantificationInfo(QuantificationInfoTypeBean value) {
		quantificationInfo = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Override
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		id = value;
	}

	/**
	 * Gets the value of the sampleRef property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSampleRef() {
		return sampleRef;
	}

	/**
	 * Sets the value of the sampleRef property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSampleRef(String value) {
		sampleRef = value;
	}

	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return -1;
	}

	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (obj instanceof ExperimentalConditionTypeBean) {
			ExperimentalConditionTypeBean condition = (ExperimentalConditionTypeBean) obj;
			if (condition.getId().equals(id))
				return true;
			return false;
		}
		return super.equals(obj);
	}

}
