//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.12.03 at 06:58:04 PM PST
//

package edu.scripps.yates.shared.model.projectCreator.excel;

import java.io.Serializable;

public enum FormatTypeBean implements Serializable {

	XLSX("xlsx"), XLS("xls"), CENSUS_CHRO_XML("census_chro_xml"), CENSUS_OUT_TXT(
			"census_out_txt"), DTA_SELECT_FILTER_TXT("dta_select_filter_txt"), FASTA("fasta");
	private final String value;

	FormatTypeBean(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static FormatTypeBean fromValue(String v) {
		for (FormatTypeBean c : FormatTypeBean.values()) {
			if (c.value.equalsIgnoreCase(v)) {
				return c;
			}
			if (c.name().equalsIgnoreCase(v))
				return c;
		}
		return null;
	}

}
