//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.12.03 at 06:58:04 PM PST
//

package edu.scripps.yates.shared.model.projectCreator.excel;

import java.io.Serializable;

import edu.scripps.yates.shared.model.interfaces.HasId;

public class LabelTypeBean extends HasId implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -1199534826603598296L;
	protected String id;
	protected Double massDiff;

	/**
	 * Gets the value of the id property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	@Override
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setId(String value) {
		id = value;
	}

	/**
	 * Gets the value of the massDiff property.
	 *
	 * @return possible object is {@link Double }
	 *
	 */
	public Double getMassDiff() {
		return massDiff;
	}

	/**
	 * Sets the value of the massDiff property.
	 *
	 * @param value
	 *            allowed object is {@link Double }
	 *
	 */
	public void setMassDiff(Double value) {
		massDiff = value;
	}

	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return -1;
	}

	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (obj instanceof LabelTypeBean) {
			LabelTypeBean label = (LabelTypeBean) obj;
			if (label.getId().equals(id))
				return true;
		}
		return super.equals(obj);
	}
}
