//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.12.03 at 06:58:04 PM PST
//

package edu.scripps.yates.shared.model.projectCreator.excel;

import java.io.Serializable;
import java.util.Date;

import javax.xml.datatype.XMLGregorianCalendar;

import edu.scripps.yates.shared.model.interfaces.HasId;

public class MsRunTypeBean implements Serializable, HasId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -503201634978626005L;
	protected String id;
	protected String path;
	protected Date date;
	protected String fastaFileRef;
	protected String enzymeResidues;
	protected String enzymeNocutResidues;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Override
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		id = value;
	}

	/**
	 * Gets the value of the path property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPath() {
		return path;
	}

	/**
	 * Sets the value of the path property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPath(String value) {
		path = value;
	}

	/**
	 * Gets the value of the date property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * Sets the value of the date property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setDate(Date value) {
		date = value;
	}

	/**
	 * Gets the value of the fastaFileRef property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFastaFileRef() {
		return fastaFileRef;
	}

	/**
	 * Sets the value of the fastaFileRef property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFastaFileRef(String value) {
		fastaFileRef = value;
	}

	/**
	 * Gets the value of the enzymeResidues property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEnzymeResidues() {
		return enzymeResidues;
	}

	/**
	 * Sets the value of the enzymeResidues property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEnzymeResidues(String value) {
		enzymeResidues = value;
	}

	/**
	 * Gets the value of the enzymeNocutResidues property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEnzymeNocutResidues() {
		return enzymeNocutResidues;
	}

	/**
	 * Sets the value of the enzymeNocutResidues property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEnzymeNocutResidues(String value) {
		enzymeNocutResidues = value;
	}

	/*
	 * Are equals if the id is the same
	 */

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof MsRunTypeBean)
			return getId().equals(((MsRunTypeBean) obj).getId());
		return super.equals(obj);
	}

	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return -1;
	}
}
