//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.12.03 at 06:58:04 PM PST
//

package edu.scripps.yates.shared.model.projectCreator.excel;

import java.io.Serializable;

import edu.scripps.yates.shared.model.interfaces.HasId;

public class RemoteFilesRatioTypeBean implements Serializable, HasId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8643810017609452096L;
	protected String numerator;
	protected String denominator;
	protected String discardDecoys;
	protected String fileRef;
	protected String msRunRef;
	protected String id;

	/**
	 * Gets the value of the numerator property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNumerator() {
		return numerator;
	}

	/**
	 * Sets the value of the numerator property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNumerator(String value) {
		numerator = value;
	}

	/**
	 * Gets the value of the denominator property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDenominator() {
		return denominator;
	}

	/**
	 * Sets the value of the denominator property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDenominator(String value) {
		denominator = value;
	}

	/**
	 * Gets the value of the discardDecoys property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDiscardDecoys() {
		return discardDecoys;
	}

	/**
	 * Sets the value of the discardDecoys property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDiscardDecoys(String value) {
		discardDecoys = value;
	}

	/**
	 * Gets the value of the fileRef property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFileRef() {
		return fileRef;
	}

	/**
	 * Sets the value of the fileRef property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFileRef(String value) {
		fileRef = value;
	}

	/**
	 * Gets the value of the msRunRef property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMsRunRef() {
		return msRunRef;
	}

	/**
	 * Sets the value of the msRunRef property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMsRunRef(String value) {
		msRunRef = value;
	}

	@Override
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
}
